
CREATE TABLE #SEQUENCE ([TYPE] INT, [NAME] NVARCHAR(256), [OWNER] NVARCHAR(256), [LEVEL] INT);
INSERT INTO #SEQUENCE
EXEC SP_MSDEPENDENCIES @INTRANS = 1 ,@OBJTYPE=3


;WITH CTE AS (
SELECT ALLTABLES.NAME, 
(SELECT NAME FROM SYS.TABLES WHERE OBJECT_ID = PARENTS.REFERENCED_OBJECT_ID ) PARENT FROM SYS.TABLES ALLTABLES
LEFT JOIN SYS.FOREIGN_KEYS PARENTS
ON ALLTABLES.OBJECT_ID = PARENTS.PARENT_OBJECT_ID 
) 
,TABLEPARENTS AS (
SELECT DISTINCT C1.NAME, PARENTS = STUFF(( SELECT	',' + PARENT
				FROM	CTE AS C2
				WHERE C2.NAME = C1.NAME
				FOR XML	PATH('')
				), 1, 1, '')
FROM CTE C1
)
SELECT TP.NAME,LO.LEVEL, TP.PARENTS 
FROM #SEQUENCE LO INNER JOIN TABLEPARENTS TP ON TP.NAME = LO.NAME




