--SELECT * FROM SYS.foreign_keys

--select * from sys.tables



;WITH CTE AS (
SELECT ALLTABLES.NAME, 
(SELECT NAME FROM SYS.TABLES WHERE OBJECT_ID = PARENTS.REFERENCED_OBJECT_ID ) PARENT FROM SYS.TABLES ALLTABLES
LEFT JOIN SYS.FOREIGN_KEYS PARENTS
ON ALLTABLES.OBJECT_ID = PARENTS.PARENT_OBJECT_ID 
) 
SELECT DISTINCT C1.NAME 'TABLE', PARENTS = STUFF(( SELECT	',' + PARENT
				FROM	CTE AS C2
				WHERE C2.NAME = C1.NAME
				FOR XML	PATH('')
				), 1, 1, '')
FROM CTE C1


